name = "biased-be"
main = "src/index.ts"
compatibility_date = "2024-03-01"

# Use the newer nodejs_compat flag for better Node.js compatibility
compatibility_flags = ["nodejs_compat"]

# Configure your database
[[d1_databases]]
binding = "DB"
database_name = "ai-asap-bot"
database_id = ""




